# Generated by Django 6.0 on 2025-12-19 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_bottlestock_options_and_more'),
        ('products', '0002_alter_bottletype_options_alter_brand_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bottlestock',
            unique_together={('bottle_type',)},
        ),
        migrations.AlterUniqueTogether(
            name='cosmeticstock',
            unique_together={('cosmetic',)},
        ),
        migrations.AlterUniqueTogether(
            name='perfumestock',
            unique_together={('perfume',)},
        ),
    ]
