# Generated by Django 6.0 on 2025-12-28 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_bottlestock_unique_together_and_more'),
        ('products', '0004_alter_bottletype_is_paid_alter_bottletype_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bottlestock',
            options={'verbose_name': 'Остаток Атомайзера', 'verbose_name_plural': 'Остатки Атомайзеров'},
        ),
        migrations.AlterField(
            model_name='bottlestock',
            name='bottle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.bottletype', verbose_name='Тип атомайзера'),
        ),
    ]
