# Generated by Django 6.0 on 2025-12-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_printqueue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='discount',
        ),
        migrations.AddField(
            model_name='sale',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(default=0, help_text='Скидка на чек (%)', verbose_name='Скидка на чек (%)'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(default=0, help_text='Скидка на позицию (%)', verbose_name='Скидка (%)'),
        ),
    ]
