# Generated by Django 6.0 on 2025-12-29 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_bottletype_options'),
        ('sales', '0005_paymentmethod_sale_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='bottle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.bottletype', verbose_name='Тип атомайзеров'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='sale_type',
            field=models.CharField(choices=[('full', 'Флакон полностью'), ('split', 'Распив'), ('cosmetic', 'Косметика'), ('gift', 'Подарок')], max_length=10, verbose_name='Тип продажи'),
        ),
    ]
