# Generated by Django 6.0 on 2025-12-23 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_bottletype_options_alter_brand_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cosmeticproduct',
            name='stock',
        ),
    ]
