# Generated by Django 6.0 on 2025-12-28 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_cosmeticproduct_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottletype',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Платный или бесплатный атомайзер', verbose_name='Платный атомайзер'),
        ),
        migrations.AlterField(
            model_name='bottletype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название атомайзера'),
        ),
    ]
