# Generated by Django 6.0 on 2025-12-29 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_bottletype_is_paid_alter_bottletype_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bottletype',
            options={'verbose_name': 'Тип атомайзеров', 'verbose_name_plural': 'Типы атомайзеров'},
        ),
    ]
